packages:
  #!| all packages in direct subdirs of packages/
  #* - "packages/*"
  - "apps/*"
  
  # all packages in subdirs of components/
  # - "components/**"
  # exclude packages that are inside test directories
  # - "!**/test/**"

  #!| Apps in  folder old-assignments
  # - "apps/*"